#port number
server:
  port: 8089
#database configuration
spring:
  servlet:
    multipart:
      max-file-size: 10MB  # 最大文件大小
      max-request-size: 10MB  # 最大请求大小
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fitness?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: 1234



#mybatis plus
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      #Configuring mybatis plus to update only non-empty and non-NULL fields on update
      update-strategy: not_empty

#Image upload
web:
  uploadpath: /Users/dann/Documents/Materials/DiplomaWork/images  #image uploading path
  load-path: file:/Users/dann/Documents/Materials/DiplomaWork/images/  #imgae accessing, loading path

#jwt配置
jwt:
  #颁发者
  issuer: itmk
  #秘钥
  secret: com.itmk
  #30分钟过期
  expiration: 30

logging:
  pattern:
    console: '%d{yyyy-MM-dd} [%thread] %-5level %logger- %msg%n'